# Generated by Django 5.2.6 on 2025-10-23 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('artist_name', models.CharField(max_length=200)),
                ('artist_genres', models.TextField()),
                ('artist_followers', models.IntegerField()),
                ('artist_popularity', models.IntegerField()),
                ('artist_externalurls', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('track_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('track_name', models.CharField(max_length=200)),
                ('track_popularity', models.IntegerField()),
                ('track_duration_ms', models.IntegerField()),
                ('track_explicit', models.BooleanField()),
                ('track_externalurls', models.URLField()),
                ('track_artistId', models.ForeignKey(db_column='artist_id', on_delete=django.db.models.deletion.CASCADE, to='main.artist')),
            ],
        ),
    ]
