# Generated by Django 5.2.6 on 2025-10-24 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='artist_externalurls',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='artist_followers',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='artist_genres',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='artist_name',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='artist_popularity',
        ),
    ]
