# Generated by Django 5.2.6 on 2025-10-24 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_artist_artist_externalurls_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='track_artistId',
        ),
        migrations.RemoveField(
            model_name='track',
            name='track_duration_ms',
        ),
        migrations.RemoveField(
            model_name='track',
            name='track_explicit',
        ),
        migrations.RemoveField(
            model_name='track',
            name='track_externalurls',
        ),
        migrations.RemoveField(
            model_name='track',
            name='track_name',
        ),
        migrations.RemoveField(
            model_name='track',
            name='track_popularity',
        ),
    ]
