# Generated by Django 5.2.6 on 2025-10-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_track_track_artistid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artist_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
