# Generated by Django 5.2.6 on 2025-10-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_artist_artist_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, unique=True)),
                ('access_token', models.CharField(max_length=500)),
                ('refresh_token', models.CharField(max_length=500, null=True)),
                ('expires_in', models.DateTimeField()),
                ('token_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Track',
        ),
        migrations.AddField(
            model_name='artist',
            name='artist_externalurls',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='artist_followers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='artist_genres',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='artist_popularity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
