# Generated by Django 5.2.6 on 2025-10-29 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_user_id_spotifytoken_spotify_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'verbose_name': 'Artist', 'verbose_name_plural': 'Artists'},
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='artist_followers',
            new_name='followers_total',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='artist_popularity',
            new_name='popularity',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='artist_id',
            new_name='spotify_id',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='artist_externalurls',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='artist_genres',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='artist_name',
        ),
        migrations.AddField(
            model_name='artist',
            name='genres',
            field=models.TextField(blank=True, default='', help_text='콤마로 구분된 장르 리스트'),
        ),
        migrations.AddField(
            model_name='artist',
            name='name',
            field=models.CharField(default='Unknown Artist', max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('spotify_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('popularity', models.IntegerField(blank=True, null=True)),
                ('release_year', models.IntegerField(blank=True, help_text='트랙이 발매된 연도', null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, default='', help_text='Track의 대표 장르 (Artist의 첫 번째 장르)', max_length=100)),
                ('ranking', models.IntegerField(help_text='사용자 Top Tracks 목록에서의 순위 (1, 2, 3...)')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='main.artist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_tracks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'ranking'],
                'unique_together': {('user', 'ranking')},
            },
        ),
    ]
